name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify the version of Python you need

      - name: Install Python Packages
        run: |
          pip install wheel setuptools
          pip install conan # Install the latest version of Conan

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@v3.30.3
        with:
          cmakeVersion: 'latest'
          ninjaVersion: 'latest'

      - name: Configure Conan Profile
        run: |
          conan profile detect --name custompr
          conan profile update -c tools.system.package_manager:mode=install custompr
          conan profile update -c tools.system.generator=Ninja custompr

      - name: Install Conan Dependencies
        run: |
          conan install . --build=missing -s build_type=Release --profile custompr

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build Project
        run: cmake --build ./build/Release/

      - name: Run Tests
        run: |
          ctest --verbose
        working-directory: ./build/Release/

      - name: Run the Executable
        run: ./build/Release/bin/TetrisGame
